### ISSUE TITLE
Compliance issue

### ISSUE THREAD

**Issue by lucasgonze** [scanoss/wfp#6]
Viral licensing requires that any derivative work must be distributed under the same or equivalent license terms. wfp combines GPL 2 code with permissively-licensed code. As a result the combination is in an uncertain state from a copyright perspective.

Proposed fix: ask the creator of crc32c.c to provide a version under the GPL, under with a dual license.

The license on crc32c.c is roughly BSD:
```
  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the author be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
```

The license on winnowing.c is GPL-2.0-or-later
```
/*
 * src/main.c
 *
 * Winnowing algorithm implementation
```

**Comment by juliancoccia** [comment]
Thanks for your report, @lucasgonze 

Generally speaking, copyleft code can contain permissive code, not the other way around. In this case, our GPL code contains a (sort of) BSD code. BSD (with exception of the 4th clause) is considered compatible with the GPL and it is quite common to re-release BSD code as GPL. This is because, provided that the original license text is preserved (and any other obligations, if any, are fulfilled), the GPL license is not contradicting any BSD license conditions.

Now, going into this particular BSD-like license:

* There is no advertising clause (which makes the BSD-4-clause incompatible with the GPL)
* There is a special provision (2) for modified code. In our case we are using the untouched, original code.
* All conditions listed in the license are being fulfilled

Therefore, we don't see any compliance issues.

Please let us know if we missed something in particular!

**Comment by lucasgonze** [comment]
@juliancoccia Thank you for this thoughtful analysis.
